development:
  adapter: mysql2
  encoding: utf8
  database: okon_db
  pool: 5
  username: okon
  password: okon#App3
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: okon_db
  pool: 5
  username: okon
  password: okon#App3
  host: 127.0.0.1
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
  database: okon_db
  pool: 5
  username: okon
  password: okon#App3
  host: 127.0.0.1
  port: 3306
